name: Block on fixup commits

on: pull_request

permissions:
  pull-requests: read

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3.6.0

      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
